services:
  - type: web
    name: my-service
    env: python
    plan: free
    pythonVersion: 3.8
    buildCommand: pip install -r requirements.txt 
    startCommand: streamlit run app/zong116.py  
